# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_libro_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='slug',
            field=models.SlugField(default='libro', editable=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='contenido',
            field=models.TextField(default='CONTENIDO VACIO', max_length=500),
        ),
    ]
