# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0005_libro_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='ISBN',
            field=models.CharField(default='00', max_length=20),
        ),
    ]
