# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0006_libro_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(default='correoautor@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='editor',
            name='estado',
            field=models.CharField(default='San Salvador', max_length=60),
        ),
        migrations.AlterField(
            model_name='editor',
            name='website',
            field=models.URLField(default='www.misitio.com'),
        ),
    ]
