# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0007_auto_20160517_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=39),
        ),
    ]
