# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0009_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
